### PR TITLE
update: error output specifies problem file

### PR DESCRIPTION
**Pull request by cgdibble**
In using this with many files iteratively, I find that having the error identify what file cause the issue would help _a ton_.

Let me know what ya think!

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@EvanHahn 👋 

@cgdibble is a current member of the Braintree SDK team (and a cool guy), if you have a minute to merge and release this, we’d be grateful.

**Comment by crookedneighbor** [comment]
Though, apparently I do have merge access in this repo still!

**Review by crookedneighbor — APPROVED** [review]

**Review by EvanHahn — APPROVED** [review]

**Comment by EvanHahn** [comment]
I'll deploy this soon!

**Comment by EvanHahn** [comment]
Published in `check-ecmascript-version-compatibility@0.2.0`!

**Comment by cgdibble** [comment]
Huzah, thank you!

**Pull request merged**
